title: Reusable Content Demonstration
author: Tony Hirst

lang: en

only_build_toc_files: true

sphinx:
  extra_extensions:
    - ou_book_theme
    - sphinxcontrib.mermaid
    - sphinx_exercise
    - sphinxcontrib.youtube
    - sphinxcontrib.video
    - sphinxcontrib.audio
  config:
    myst_heading_anchors: 3
    numfig: true
    numfig_format: {'figure':'Figure %s'}
    numfig_secnum_depth: 1 #eg 0:1 1:2.1 2:3.2.1
    html_theme: ou_book_theme
parse:
  myst_enable_extensions:
    - colon_fenceparse
    - amsmath
    - dollarmath

ou:
  module_code: XXX
  module_title: YYY
  block: 0
  presentation: ZZZ
  first_published: YYYY
  isbn:
  edition:
  block_title: QQQQ
  image_path_prefix: https://specified.path/to/image/directory/
  audio_path_prefix: https://specified.path/to/audio/directory/