name: deploy-book

on:
  release:
    types: [published]
  workflow_dispatch:

# This job installs dependencies, builds the book, and pushes it to `gh-pages`
jobs:
  deploy-book:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # Install dependencies
    - name: Set up Python 3.11
      uses: actions/setup-python@v1
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        pip install jupyter-book ou-jupyter-book-tools
        pip install ou_book_theme sphinxcontrib.mermaid sphinxcontrib-youtube sphinx-exercise
    # Build the book
    - name: Build the book
      run: |
        jupyter-book build .
        touch ./_build/html/.nojekyll
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Build the OU-XML
      run: |
        pip install https://github.com/innovationOUtside/ou-xml-validator/archive/refs/heads/main.zip
        jb build --builder custom --custom-builder xml .
        ouseful_obt .
        mkdir -p /var/tmp/dist
        cp -rf _build/ouxml /var/tmp/dist/
        cp -rf _build/ouxml ./_build/html
    # Push the book's HTML to github-pages
    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3.6.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_build/html
    - name: Upload docs bundle
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: ${{github.event.inputs.module}}_docs_bundle
        path: /var/tmp/dist
